server:
  port: 80

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/computerstore?serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: 123456

# mp配置
mybatis-plus:
  mapper-locations: classpath*:**/mapper/xml*/*.xml*
  configuration:
    #驼峰命名默认true
    map-underscore-to-camel-case: true
    #开启日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #雪花算法
      id-type: auto
salt:
  passwd: huangjy


logging:
  level:
    com.example.mapper.OrderMapper: debug

alipay:
  appId: 2021000122602661
  appPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDjknFKlqj6fwVZodKhqYew366TAUfAEF2AOAAmkyUOtMMlS6sG2WSw+onBWsW0zpsqiICdFX0DSPKoNCY39xs4JhL/yMugfrRUrfEWTWZnwCmEN5wkAiYO4DitIjzIUthVX7o7FPFP2ZDjx1qHSfG5uBpCBN2bUzJvxOwDZc4MyxOKvO57J/kIGcTFkE/gJbIuJBFKIGmfzFpQ/CsZXwY1U2FkJpmCS4Fn8l1fyNg4lVaMD0uyPedlp/jIXSvumWnsrz4j64hlatote5ZFoVm5kdBmjzTyw22KkA3+JjB4hG0Np5OxLT7sjRV9OSJuj8BnMEpFzon75XfBzpWPyI8PAgMBAAECggEAXCB1sq9pOvdfEBkdrwp1fxoejy6OgGdfor+I+BTLhLeS5K9MTlqFk8vpJph7vyWA1WgrQOxpDoJikcuCyVdE8qcfO+Nq489Ha5x7I/8zfL7jT74/fKhOBempqBVbK/G12GIHf1GMGzpFmKCkum4p6HhqUN2tZOr6WRsMPJfjIXP1B2g5SLXiSkUmX/Zqy7pIlCyXZ8uFu4kSzrgLUf6d+/ZBYbGO++YK49F/syPy3Xb80GyZiyR/dqox7svFBEJ+RKec+SnJXT7loL1D/uDk2M3LD1m3vZUszz0r9tSIiRbZikbKKO+9U1mvHO0/GXGzwKCxtYQYPybXbYho+OvfQQKBgQD+EGXx4UfSZxyRqrRAUufr13Jdcxkzq6uYSbWG6uTe6IP0OKIC0WnQ3Ve9Brqx34sg6RHvwt4A21xt48c8OnA1id37Pl25f6bCTVoQqc3OcoH4YjaHJ/7jy/D6FbU6icmg3v0VobMUA2RwE0fHLAQX1Te6bzP3vdG3TXDC3AbYLwKBgQDlTl3PxaRp0tnvhYhFN/PF3v7cVV1JApCbW1wK6j/B5t2FPD2JLYTFWxkIub4XW9lkX3YbrytOog3v3ue+PgM4gTaUkZl6fyLAhpuTZ88lj07fe+aYyHjYyTTlsFYuUNj5T1MxYbyW5JNLBmFJId2xcbWwv9L95R8Qh1uDFZcfIQKBgBVjMgHLsi0fKwOEOEpV8FolN+ZwAwYbhIV8ZwClk4DEWB9eCR1tnZfMmk86WssQg3jQxgbGA8RUsxI5I5OJY9rN8VbuKBuuiE5BDrzqXn3rm89aDTcRgd6RU4bp/uifos6dFvcUNqwPoQviQ5+br/iFpXxXUiuf2iCxLzXoKddXAoGAe3fu22k4ViLKZkYoUd0GzYx8/naYfC99XambreTj36xHqu381FhGHV4n5KLe0AUM0Rb1qYJwdy6bAoWrkqwhX9NzaBvd4C+ErtXL/1ruFvNLLNqyF6IaL+BnMyX3wYiWy+cCjJxrx3PcO5F74LzzehAYHMus+DjeuS+o/rQpYwECgYALIvrqIXbYQob2nCIOFM3pk7YbHw/F2xrQcxkWlCN0kosaDxwQuCU3gse7VAQ92NWXsqO60lyRR0nuEvGDW7hsIWP5DwSryq313cJ+cznOI4Q15M+TNn5qUJekUptRrTw1F4Err0GQrajX9y6/Dpn62qL5ymFS5sua2DK+kyp5Ng==
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAj63FTZRa+qGiPG6cgUu5mvkVgSiG7pXfqGuD4ElnsvO/G00DyhdqFR5KJRZN1rAWeSt1OwPEfRJyf1TkszozAvRG1PngPmQAjfKqLCSXIDUUClsuwvjLQ6T/+MbOoN0vylPP1FlbBkaxw5x2SAEHSj/nqVyxWGZNLGnc3RIMbmQSzugvD+F9taqrTH9kdWlO/uRFE2GhhnNZpwWiEsHoKNx8wucTNI5uFNEGk51khdtFxqcoHS+EqQEnyt84LHHkCHHdq7xE1jYfbVqHnkAxAVrceVFwI7VvJ+f8rOJ4jtZoNilW+zD6Py0ylnd6BtTv2GIDqnfuf+7pqMSNwL1GXQIDAQAB
  notifyUrl: http://8dtv8h.natappfree.cc/alipay/notify




